version: '3'

services:
  api:
    build: .
    container_name: api
    restart: unless-stopped
    environment:
      PORT: 3000
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: db
      JWT_SECRET: secret
      ADMIN_LOGIN: admin
      ADMIN_PASSWORD: admin
    volumes:
      - .:/app
    depends_on:
      - db
    ports:
      - 3000:3000
    command: sh -c "npm run start"

  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 3306:3306
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db:
